/**
 * Cloudflare Worker entrypoint (wrangler.jsonc "main": "./worker.ts").
 *
 * This file is bundled by WRANGLER, not by Next.js — it is excluded from
 * `tsconfig.json` because it imports `.open-next/worker.js`, which is only
 * generated by `opennextjs-cloudflare build`.
 *
 * It re-exports the default OpenNext fetch handler and adds a `scheduled`
 * handler backed by Cron Triggers (see `triggers.crons` in wrangler.jsonc).
 */
// @ts-nocheck — resolved by wrangler bundling after `opennextjs-cloudflare build`
export { default } from "./.open-next/worker.js";

import { initD1, setDb } from "./src/lib/db";
import { runScheduledJobs } from "./src/server/cron";

/**
 * Cron Triggers (UTC — see wrangler.jsonc for PT->UTC mapping):
 *  - "0 16 * * *"  daily 8:00 AM PT -> birthday notifications
 *  - "0 17 * * 1"  Monday 9:00 AM PT -> audiogram reminders
 */
export async function scheduled(event: ScheduledEvent, env: CloudflareEnv, ctx: ExecutionContext) {
  console.log("[Cron] scheduled event:", event.cron);

  // The jobs use the shared `db` from src/lib/db; give them the real binding
  // (getCloudflareContext() has no request context to read it from here).
  setDb(env.DB);
  await initD1(env.DB);

  const summary = await runScheduledJobs();
  console.log("[Cron] completed:", summary);

  // Note: the fetch handler from .open-next/worker.js remains the default
  // export; this scheduled handler runs in the same isolate.
  void ctx;
}
